version: 2

sources:
  - name: calls_table
    schema: raw
    tables:
      - name: raw_call_dataset

  - name: clv_table
    schema: raw
    tables:
      - name: raw_clv_dataset
  
  - name: customer_table
    schema: raw
    tables:
      - name: raw_customer_dataset
  
  - name: lead_table
    schema: raw
    tables:
      - name: raw_lead_dataset

  - name: marketing_cost_table
    schema: raw
    tables:
      - name: raw_marketing_costs_dataset

  - name: sales_cost_table
    schema: raw
    tables:
      - name: raw_sales_cost_dataset