WITH stg_customer AS (

SELECT 
CONTACT_ID,
TO_DATE(SUBSTRING(CUSTOMER_DATE, 1, 10), 'DD.MM.YYYY') AS CUSTOMER_DATE,
CONTRACT_LENGTH,
CURRENT_TIMESTAMP AS _stg_datetime
FROM {{ ref('dl_customers') }} 

)


SELECT * FROM stg_customer
WHERE CONTRACT_LENGTH IS NOT NULL
