


WITH stg_calls AS(

SELECT 
CONTACT_ID,
TRIAL_BOOKED,
TO_DATE(TRIAL_DATE, 'DD.MM.YYYY') AS TRIAL_DATE,
CALL_ATTEMPTS,
TRY_CAST(REGEXP_REPLACE(TOTAL_CALL_DURATION, '^([^.]+\.[^.]+)\..*', '\\1') AS DECIMAL(18,2)) AS TOTAL_CALL_DURATION,
CALLS_30,
CURRENT_TIMESTAMP AS _stg_datetime
FROM {{ref('dl_calls')}}

)

SELECT * FROM stg_calls
